Repository iiandmy/fluxops-frontend, pull requests merged in 2025-02, with the labels that each got.

#7 Feature/dashboard page improvements
  package.json
  src/components/index.ts
  src/components/plate/plate.module.css
  src/components/separator/index.ts
  src/components/separator/separator.module.css
  src/components/separator/separator.tsx
  src/constants/dimensions.ts
  src/constants/index.ts
  src/constants/page-titles.ts
  src/hooks/clients/index.ts
  src/hooks/clients/use-clients.hook.ts
  src/index.css
  src/main.tsx
  src/modules/dashboard/components/client-card/client-card.module.css
  src/modules/dashboard/components/client-card/client-card.skeleton.tsx
  src/modules/dashboard/components/client-card/client-card.tsx
  src/modules/dashboard/components/client-card/index.ts
  src/modules/dashboard/components/client-card/types.ts
  src/modules/dashboard/components/client-list/client-list.module.css
  src/modules/dashboard/components/client-list/client-list.skeleton.tsx
  src/modules/dashboard/components/client-list/client-list.tsx
  src/modules/dashboard/components/clients-dashboard-card/clients-dashboard-card.module.css
  src/modules/dashboard/components/clients-dashboard-card/clients-dashboard-card.tsx
  src/modules/dashboard/components/clients-dashboard-card/index.ts
  src/modules/dashboard/components/index.ts
  src/modules/dashboard/pages/page.module.css
  src/modules/dashboard/pages/page.tsx
  src/modules/dashboard/widgets/clients/clients.module.css
  src/modules/dashboard/widgets/clients/clients.tsx
  src/modules/dashboard/widgets/clients/index.ts
  src/modules/dashboard/widgets/index.ts
  yarn.lock
Labels: enhancement

#9 Feat: Add Header
  src/components/header/config.ts
  src/components/header/header.module.css
  src/components/header/header.tsx
  src/components/layout/layout.module.css
  src/index.css
Labels: enhancement

#10 Feature/theme
  README.md
  src/components/header/header.module.css
  src/components/header/header.tsx
  src/constants/index.ts
  src/constants/theme.ts
  src/hooks/clients/use-clients.hook.ts
  src/hooks/index.ts
  src/hooks/redux-hooks.ts
  src/index.css
  src/modules/dashboard/components/connection-list/connection-list.module.css
  src/store/root-reducer.ts
  src/store/theme/index.ts
  src/store/theme/slice.ts
Labels: enhancement

#20 Resource Capacity Widget
  src/components/section/section.tsx
  src/components/separator/separator.module.css
  src/index.css
  src/modules/dashboard/components/index.ts
  src/modules/dashboard/components/resource-capacity-item/index.ts
  src/modules/dashboard/components/resource-capacity-item/resource-capacity-item.module.css
  src/modules/dashboard/components/resource-capacity-item/resource-capacity-item.tsx
  src/modules/dashboard/helpers/get-resource-capacity-color.ts
  src/modules/dashboard/helpers/index.ts
  src/modules/dashboard/pages/page.module.css
  src/modules/dashboard/pages/page.tsx
  src/modules/dashboard/widgets/index.ts
  src/modules/dashboard/widgets/resource-capacity/index.ts
  src/modules/dashboard/widgets/resource-capacity/resource-capacity.module.css
  src/modules/dashboard/widgets/resource-capacity/resource-capacity.tsx
  src/utils/mocks/index.ts
  src/utils/mocks/resource-capacity.ts
Labels: feature

#22 Dark Theme
  .prettierrc
  .stylelintignore
  src/components/header/header.module.css
  src/components/layout/layout.module.css
  src/components/separator/separator.module.css
  src/lib/env.ts
  src/main.tsx
  src/modules/dashboard/components/connection-filters/connection-filters.module.css
  src/modules/dashboard/components/connection-list/connection-card/connection-card.module.css
  src/modules/dashboard/components/resource-capacity-item/resource-capacity-item.module.css
  src/store/app-store.ts
  src/styles/dark.css
  src/styles/index.css
  src/styles/providers/index.ts
  src/styles/providers/theme.tsx
Labels: enhancement

#21 feat: implement script template section widget
  src/components/section/section.module.css
  src/modules/dashboard/components/index.ts
  src/modules/dashboard/components/script-template-list/index.ts
  src/modules/dashboard/components/script-template-list/script-template-item/index.ts
  src/modules/dashboard/components/script-template-list/script-template-item/script-template-item.module.css
  src/modules/dashboard/components/script-template-list/script-template-item/script-template-item.skeleton.tsx
  src/modules/dashboard/components/script-template-list/script-template-item/script-template-item.tsx
  src/modules/dashboard/components/script-template-list/script-template-list.module.css
  src/modules/dashboard/components/script-template-list/script-template-list.skeleton.tsx
  src/modules/dashboard/components/script-template-list/script-template-list.tsx
  src/modules/dashboard/pages/page.tsx
  src/modules/dashboard/types.ts
  src/modules/dashboard/widgets/index.ts
  src/modules/dashboard/widgets/script-templates/config.ts
  src/modules/dashboard/widgets/script-templates/index.ts
  src/modules/dashboard/widgets/script-templates/script-templates.module.css
  src/modules/dashboard/widgets/script-templates/script-templates.tsx
  src/styles/index.css
Labels: feature

#26 Command Log Widget
  index.html
  src/components/header/header.module.css
  src/components/section/section.tsx
  src/hooks/index.ts
  src/hooks/use-tooltip.tsx
  src/modules/dashboard/components/command-log-list/command-log-item/command-log-item.module.css
  src/modules/dashboard/components/command-log-list/command-log-item/command-log-item.skeleton.tsx
  src/modules/dashboard/components/command-log-list/command-log-item/command-log-item.tsx
  src/modules/dashboard/components/command-log-list/command-log-item/index.ts
  src/modules/dashboard/components/command-log-list/command-log-list.module.css
  src/modules/dashboard/components/command-log-list/command-log-list.skeleton.tsx
  src/modules/dashboard/components/command-log-list/command-log-list.tsx
  src/modules/dashboard/components/command-log-list/index.ts
  src/modules/dashboard/components/connection-list/connection-card/connection-card.module.css
  src/modules/dashboard/components/connection-list/connection-card/connection-card.tsx
  src/modules/dashboard/components/index.ts
  src/modules/dashboard/components/resource-capacity-item/resource-capacity-item.module.css
  src/modules/dashboard/pages/page.module.css
  src/modules/dashboard/pages/page.tsx
  src/modules/dashboard/types.ts
  src/modules/dashboard/widgets/command-logs/command-logs.module.css
  src/modules/dashboard/widgets/command-logs/command-logs.tsx
  src/modules/dashboard/widgets/command-logs/config.ts
  src/modules/dashboard/widgets/command-logs/index.ts
  src/modules/dashboard/widgets/index.ts
  src/modules/dashboard/widgets/script-templates/script-templates.module.css
  src/modules/dashboard/widgets/script-templates/script-templates.tsx
  src/store/clients/__mock__/index.ts
  src/styles/dark.css
  src/styles/index.css
Labels: feature, enhancement

#29 Feature: Typography
  eslint.config.js
  src/components/header/header.module.css
  src/components/header/header.tsx
  src/components/index.ts
  src/components/section/section.tsx
  src/components/typography/body/body.module.css
  src/components/typography/body/body.tsx
  src/components/typography/body/index.ts
  src/components/typography/font-size.module.css
  src/components/typography/font-weight.module.css
  src/components/typography/headlines/headlines.module.css
  src/components/typography/headlines/headlines.tsx
  src/components/typography/headlines/index.ts
  src/components/typography/index.ts
  src/components/typography/line-height.module.css
  src/components/typography/types.ts
  src/components/typography/typography.tsx
  src/modules/dashboard/components/command-log-list/command-log-item/command-log-item.module.css
  src/modules/dashboard/components/resource-capacity-item/resource-capacity-item.module.css
  src/styles/index.css
Labels: feature, enhancement

#28 Feature: Rework Button Component
  .gitignore
  README.md
  src/components/button/button.module.css
  src/components/button/button.tsx
  src/components/header/header.module.css
  src/components/header/header.tsx
  src/modules/dashboard/components/connection-filters/connection-filters.module.css
  src/modules/dashboard/components/connection-filters/connection-filters.tsx
  src/modules/dashboard/components/script-template-list/script-template-item/script-template-item.module.css
  src/modules/dashboard/components/script-template-list/script-template-item/script-template-item.tsx
  src/styles/dark.css
  src/styles/index.css
Labels: enhancement

#31 docs: write README.md and LICENSE
  LICENSE
  README.md
Labels: documentation

#32 Feature: Fallback Pages
  .prettierignore
  .prettierrc
  .stylelintignore
  eslint.config.js
  src/app/app-router.tsx
  src/app/layout/base-layout.tsx
  src/assets/images/404.png
  src/components/button/button.module.css
  src/components/button/button.tsx
  src/components/error/error.module.css
  src/components/error/error.tsx
  src/components/error/index.ts
  src/components/header/header.tsx
  src/components/image/image.module.css
  src/components/image/image.tsx
  src/components/image/index.ts
  src/components/index.ts
  src/components/loading/index.ts
  src/components/loading/loading.module.css
  src/components/loading/loading.tsx
  src/components/not-found/index.ts
  src/components/not-found/not-found.module.css
  src/components/not-found/not-found.tsx
  src/components/typography/body/body.module.css
  src/components/typography/body/body.tsx
  src/components/typography/line-height.module.css
  src/components/typography/types.ts
  src/constants/app-routes.ts
  src/constants/index.ts
  src/constants/url.ts
  src/main.tsx
  src/modules/automation/pages/index.ts
  src/modules/automation/pages/page.tsx
  src/modules/clients/pages/index.ts
  src/modules/clients/pages/page.tsx
  src/modules/dashboard/components/script-template-list/script-template-item/script-template-item.tsx
  src/modules/dashboard/pages/index.ts
  src/modules/dashboard/pages/page.tsx
  src/modules/settings/pages/index.ts
  src/modules/settings/pages/page.tsx
  src/modules/users/pages/index.ts
  src/modules/users/pages/page.tsx
  src/styles/providers/theme.module.css
  src/styles/providers/theme.tsx
Labels: feature

#33 Refactor: sort imports
  .prettierrc
  README.md
  src/api/base-query.ts
  src/app/app-router.tsx
  src/app/index.ts
  src/app/layout/base-layout.tsx
  src/components/error/error.tsx
  src/components/header/header.tsx
  src/components/image/image.tsx
  src/components/loading/loading.tsx
  src/components/not-found/not-found.tsx
  src/components/section/section.tsx
  src/components/typography/body/body.tsx
  src/components/typography/headlines/headlines.tsx
  src/hooks/redux-hooks.ts
  src/main.tsx
  src/modules/automation/pages/page.tsx
  src/modules/clients/pages/page.tsx
  src/modules/dashboard/components/command-log-list/command-log-item/command-log-item.tsx
  src/modules/dashboard/components/command-log-list/command-log-list.tsx
  src/modules/dashboard/components/connection-filters/connection-filters.tsx
  src/modules/dashboard/components/connection-list/connection-list.skeleton.tsx
  src/modules/dashboard/components/connection-list/connection-list.tsx
  src/modules/dashboard/components/connection-summary/connection-summary.tsx
  src/modules/dashboard/components/script-template-list/script-template-item/script-template-item.tsx
  src/modules/dashboard/components/script-template-list/script-template-list.skeleton.tsx
  src/modules/dashboard/components/script-template-list/script-template-list.tsx
  src/modules/dashboard/pages/page.tsx
  src/modules/dashboard/widgets/command-logs/command-logs.tsx
  src/modules/dashboard/widgets/connections/connections.tsx
  src/modules/dashboard/widgets/resource-capacity/resource-capacity.tsx
  src/modules/dashboard/widgets/script-templates/script-templates.tsx
  src/modules/settings/pages/page.tsx
  src/modules/users/pages/page.tsx
  src/store/app-store.ts
  src/store/clients/slice.ts
  src/store/root-reducer.ts
  src/store/session/slice.ts
  src/store/theme/slice.ts
  src/styles/providers/theme.tsx
Labels: enhancement

#35 Feature: Core List Component
  src/components/index.ts
  src/components/list/gap.module.css
  src/components/list/index.ts
  src/components/list/list.module.css
  src/components/list/list.tsx
  src/modules/dashboard/components/command-log-list/command-log-item/command-log-item.skeleton.tsx
  src/modules/dashboard/components/command-log-list/command-log-list.module.css
  src/modules/dashboard/components/command-log-list/command-log-list.skeleton.tsx
  src/modules/dashboard/components/command-log-list/command-log-list.tsx
  src/modules/dashboard/components/connection-filters/connection-filters.module.css
  src/modules/dashboard/components/connection-filters/connection-filters.tsx
  src/modules/dashboard/components/connection-list/connection-list.skeleton.tsx
  src/modules/dashboard/components/connection-list/connection-list.tsx
  src/modules/dashboard/widgets/command-logs/command-logs.tsx
Labels: feature
